"""
Author: Sam Nooij
Organisation: Utrecht University
Department: Clinical Infectiology (KLIF), Infectious Diseases & Immunology,
  Biomolecular Health Sciences, Faculty of Veterinary Medicine
Date: 2025-01-17

Workflow for assembling MinION long-read metagenomes, taxonomic classification
and identification of antibiotic resistance genes, based on previous work by
Aldert Zomer (from the same department). Now extended with raw read quality-
control and filtering.

Input: (Gzipped) Fastq files of relevant metagenomic samples
Output: (various)

Example use:
    $ snakemake --profile config

N.B. Variables are set in the configuration files under `config`.
"""

# Step 1: Load configuration
# ---------------------------------------------------------


configfile: Path("config/parameters.yaml")


# Log messages
onstart:
    print("\n--- Starting analysis! ---\n")


onsuccess:
    print("\n --- Workflow finished! ---\n")


onerror:
    print("\n --- An error occurred! ---\n")


# Step 2: Load rules that do the work
# ---------------------------------------------------------
include: "rules/helper_functions.smk"
include: "rules/preprocess_reads.smk"
include: "rules/assemble_metagenomes.smk"
include: "rules/screen_resistance_genes.smk"
include: "rules/screen_resistance_mutations.smk"
include: "rules/classify_contigs.smk"
include: "rules/strict-classify_contigs.smk"
include: "rules/generate_mags.smk"


# Step 3: specify target outputs
# ---------------------------------------------------------


rule all:
    input:
        # Summary of the input read quality control (by Fastplong)
        "results/read_qc_summary.csv",
        # Metagenomic assemblies (by Flye)
        expand("results/assembly/{sample}/assembly.fasta", sample=SAMPLES),
        # Simple assembly statistics (by seqkit)
        "results/assembly/assembly_statistics-seqkit.tsv",
        # Per-contig coverage stats
        "results/contig_coverage.csv",
        # Antibiotic resistance gene screening (by KMA)
        "results/resistance_genes-reads/summary.tsv",
        expand(
            "results/resistance_genes/{sample}.hmm.{suffix}",
            sample=SAMPLES,
            suffix=["aln", "frag.gz", "fsa", "res"],
        ),
        # Antibiotic resistance mutations (by MetaPointFinder)
        expand(
            "results/resistance_mutations/{sample}/{sample}.{mol}.updated_table_with_scores_and_mutations.tsv",
            sample=SAMPLES,
            mol=["dna", "prot"],
        ),
        expand(
            "results/resistance_mutations/{sample}/{sample}.{infix}.summary.txt",
            sample=SAMPLES,
            infix=["class.dna", "class.prot", "gene.dna", "gene.prot"],
        ),
        # Taxonomic classifications (by Centrifuger)
        expand(
            "results/taxonomic_classification/{sample}/centrifuger_masked{strictness}{extension}",
            sample=SAMPLES,
            strictness=["", "-strict"],
            extension=[".tsv", "-quant.tsv"],
        ),
        # Microbiota profiles (TaxonKit + custom R script)
        expand(
            "results/microbiota_profile/{sample}{strictness}-per_{unit}.tsv",
            sample=SAMPLES,
            unit=["contig", "species"],
            strictness=["", "-strict"],
        ),
        # Chromosome/plasmid/virus predictions (geNomad)
        expand(
            "results/plasmid_prediction/{sample}/assembly_aggregated_classification/assembly_aggregated_classification.tsv",
            sample=SAMPLES,
        ),
        # Concatenated stats from Flye,
        "results/assembly_stats-concatenated.tsv.gz",
        # Centrifuger,
        "results/classifications-concatenated.tsv.gz",
        "results/strict_classifications-concatenated.tsv.gz",
        # and geNomad
        "results/plasmid_predictions-concatenated.tsv.gz",
        "results/virus_predictions-concatenated.tsv.gz",
        # And a complete summary of assembly, ARG screening, and classification
        "results/assembly_database.csv.gz",
        # Plus a summary of antibiotic resistance mutations with further annotations
        "results/mutation_database.csv.gz",
    default_target: True
