# Snakemake config file for long-read assembly, classification and antibiotic resistance screening

### 1. Input/output parameters ###

input_list: "resources/batches/batch_1.txt"

### 2. Tool-specific parameters ###

download_raw_reads:
  threads: 4

fastplong:
  threads: 3

subsample_samples:
  threads: 4

flye:
  threads: 12

minimap2:
  threads: 8

simple_stats:
  threads: 4

kma:
  threads: 12

metapointfinder:
  threads: 8

centrifuger:
  threads: 12

semibin:
  threads: 12

metabat2:
  threads: 12

vamb:
  threads: 12

gtdbtk:
  threads: 12

genomad:
  threads: 12
