# Snakemake config file for long-read assembly, classification and antibiotic resistance screening

### 1. Input/output parameters ###

input_directory: "data/raw/"
output_directory: "data/tmp/"

### 2. Tool-specific parameters ###

flye:
  threads: 12

kma:
  threads: 12
  database: "/mnt/data/db/KMA/ResFinder/ResFinder"

centrifuger:
  threads: 12
