# Snakemake config file for long-read assembly, classification and antibiotic resistance screening

### 1. Input/output parameters ###

input_directory: "data/"

### 2. Tool-specific parameters ###

fastplong:
  threads: 3

flye:
  threads: 12

minimap2:
  threads: 8

metaquast:
  threads: 3

simple_stats:
  threads: 4

kma:
  threads: 12

metapointfinder:
  threads: 8

centrifuger:
  threads: 12

semibin:
  threads: 12

metabat2:
  threads: 12

vamb:
  threads: 12

gtdbtk:
  threads: 12

genomad:
  threads: 12
