# Snakemake config file for long-read assembly, classification and antibiotic resistance screening

### 1. Input/output parameters ###

input_directory: "data/raw/"
output_directory: "data/tmp/"

### 2. Tool-specific parameters ###

fastplong:
  threads: 3

flye:
  threads: 12

metaquast:
  threads: 3

simple_stats:
  threads: 4

kma:
  threads: 12
  database: "/mnt/data/db/KMA/ResFinder/ResFinder"

centrifuger:
  threads: 12

genomad:
  threads: 12
  database: "data/genomad_db/"
